version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_pokemon
      MYSQL_USER: pokemon
      MYSQL_PASSWORD: pokemon
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    build: ./app
    ports:
      - "8080:80"
    volumes:
      - ./app/src:/var/www/html
    depends_on:
      - db
